subgraphs:
  inventory:
    routing_url: http://localhost:4000/inventory
    schema:
      file: src/subgraphs/inventory/inventory.graphql
  products:
    routing_url: http://localhost:4000/products
    schema:
      file: src/subgraphs/products/products.graphql
  users:
    routing_url: http://localhost:4000/users
    schema:
      file: src/subgraphs/users/users.graphql